Few new plugins to include in the index
drone/drone-plugin-index pull request #301
Opened 2021-02-06 15:01 UTC by n0guest

Hello.

This PR contains information about following plugins:

* [OSSHelp/drone-alertmanager](https://hub.docker.com/r/osshelp/drone-alertmanager)
* [OSSHelp/drone-git-mirror](https://hub.docker.com/r/osshelp/drone-git-mirror)
* [OSSHelp/drone-linter](https://hub.docker.com/r/osshelp/drone-linter)
* [OSSHelp/drone-molecule](https://hub.docker.com/r/osshelp/drone-molecule)

Plus new logo for:

- Prometheus

Please, include these in the public catalog of plugins for Drone CI. If there is anything needed to be changed, please, let me know.

Thank you.

2021-02-09 12:40 UTC, n0guest commented
@bradrydzewski or @tboerger, could someone, please, take a look at this PR? In short - we want to add few new plugins to the public index.

Thank you.

2021-02-20 00:31 UTC, appleboy requested changes

2021-02-20 00:31 UTC, appleboy commented on content/OSSHelp/drone-alertmanager/index.md
> +    <# Deploy steps #>
remove the line?

2021-02-20 00:43 UTC, n0guest commented on content/OSSHelp/drone-alertmanager/index.md
> +    <# Deploy steps #>
Done

2021-02-20 00:54 UTC, appleboy approved these changes
LGTM. need other maintainer approval.

2022-05-05 15:06 UTC, d1wilko commented
Hi,

We have recently updated the drone plugin index and docs are no longer written in markdown - they are now a more consistent yaml format e.g. [docker](https://github.com/drone/drone-plugin-index/blob/master/plugins/docker/content.yaml)

Please have a look at the new readme if you would like to run the new plugin index [readme](https://github.com/drone/drone-plugin-index/blob/master/README.md)

If you would still like to add documentation to the plugins index can you change the format to
- An individual folder per plugin inside the `plugins` folder
- a `content.yaml` file that follows the format in the example above - this is for quick discovery, not full documentation
- an `original.md` file that can contain the markdown you have already written
- a logo image inside the `public/logos` folder

Thanks :)

2022-07-04 15:54 UTC, closed without merging