add gitee pulls plugin
drone/drone-plugin-index pull request #316
Opened 2021-12-30 12:52 UTC by kit101

2022-05-05 15:02 UTC, d1wilko commented
Hi,

We have recently updated the drone plugin index and docs are no longer written in markdown - they are now a more consistent yaml format e.g. [docker](https://github.com/drone/drone-plugin-index/blob/master/plugins/docker/content.yaml)

Please have a look at the new readme if you would like to run the new plugin index [readme](https://github.com/drone/drone-plugin-index/blob/master/README.md)

If you would still like to add documentation to the plugins index can you change the format to
- An individual folder per plugin inside the `plugins` folder
- a `content.yaml` file that follows the format in the example above - this is for quick discovery, not full documentation
- an `original.md` file that can contain the markdown you have already written
- a logo image inside the `public/logos` folder

Thanks :)

2022-05-05 15:55 UTC, kit101 commented
> Hi,
> 
> We have recently updated the drone plugin index and docs are no longer written in markdown - they are now a more consistent yaml format e.g. [docker](https://github.com/drone/drone-plugin-index/blob/master/plugins/docker/content.yaml)
> 
> Please have a look at the new readme if you would like to run the new plugin index [readme](https://github.com/drone/drone-plugin-index/blob/master/README.md)
> 
> If you would still like to add documentation to the plugins index can you change the format to
> 
> * An individual folder per plugin inside the `plugins` folder
> * a `content.yaml` file that follows the format in the example above - this is for quick discovery, not full documentation
> * an `original.md` file that can contain the markdown you have already written
> * a logo image inside the `public/logos` folder
> 
> Thanks :)

I will update these contents in these days. Thanks :)

2022-05-05 16:36 UTC, kit101 commented
Hi, @d1wilko . I have finished it.

2022-05-05 19:42 UTC, d1wilko requested changes
Thank you very much for updating, it looks great.

Can I ask you to remove some lines from the example - we want to keep it extremely simple with more complicated examples in the markdown and repo readme :)

2022-05-05 19:42 UTC, d1wilko commented on plugins/gitee-pulls/content.yaml
> +  ---
can you remove this line?

2022-05-05 19:42 UTC, d1wilko commented on plugins/gitee-pulls/content.yaml
> +  #  PLUGIN_GITEE_FAILURE_LABEL: drone-build/failure,DB2828
can you remove these lines?

2022-05-05 19:42 UTC, d1wilko commented on plugins/gitee-pulls/content.yaml
> +      # should set `is_running: true` in the first step
can you remove this line?

2022-05-05 19:42 UTC, d1wilko commented on plugins/gitee-pulls/content.yaml
> +      - success
can you remove these lines?

2022-05-06 04:26 UTC, kit101 commented
> Thank you very much for updating, it looks great.
> 
> Can I ask you to remove some lines from the example - we want to keep it extremely simple with more complicated examples in the markdown and repo readme :)

I couldn't agree more. I've removed these code. :)

2022-05-06 08:34 UTC, d1wilko approved these changes
Looks good to me :) - thank you

2022-05-06 08:34 UTC, merged