Clarify that docker plugin can accept multiple tags
drone/drone-plugin-index pull request #394
Opened 2023-02-27 03:30 UTC by scubbo

See [forum
post](https://community.harness.io/t/possible-error-in-drone-docker-plugin-documentation/13434).

I used the Go syntax for collections types since Go looks like Drone's primary language.

It would be nice to have multiple examples (showing that `tags` can be both a single string or an array), but from a look at `scripts/buildPluginJson.mjs` it looks like the system only supports a single `example`, and that's probably a more-significant change than should be submitted without discussion.

There are probably _plenty_ of other plugin-variables which have a similar signature, but I suspect we can't easily search for that from this repo alone.

2023-02-27 16:49 UTC, d1wilko requested changes
Hey, thanks for the PR :)

Can you remove the `package-lock.json` as you haven't made any changes to the `package.json`

I think it's ok if we change the type to `array` here for simplicity - even if the array only has one element - I'm hesitant to add too many enums for type

it does open up a bigger consideration about arrays having types... - but I think it needs to be clean, not simply adding more enums to the schema

I'll give it some thought :)

2023-02-27 16:49 UTC, d1wilko commented on plugin-validation/plugin-schema.json
> +                "string or []string"
I think we can remove this - it will be covered by `array`

2023-02-27 16:49 UTC, d1wilko commented on plugins/docker/content.yaml
> +    type: "string or []string"
let's just make this `array` for now

2023-02-28 16:47 UTC, scubbo commented on plugins/docker/content.yaml
> +    type: "string or []string"
Sure thing, will do!

2023-03-04 20:46 UTC, scubbo commented
Sorry for the delay!

2023-03-06 09:07 UTC, d1wilko approved these changes
LGTM - thank you :)

2023-03-06 09:07 UTC, merged